version: '3'
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./data:/docker-entrypoint-initdb.d/:ro
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dev']
      interval: 5s
      timeout: 5s
      retries: 5
  